# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Row < Formula
  desc "Filter stdin lines by range"
  homepage "https://github.com/suominentoni/row"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suominentoni/row/releases/download/v0.1.0/row_0.1.0_darwin_amd64.tar.gz"
      sha256 "236f77484e03d14da5214e7ebd6be6199ab1b5c274c480a89dad080b97a3f319"

      def install
        bin.install "row"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suominentoni/row/releases/download/v0.1.0/row_0.1.0_darwin_arm64.tar.gz"
      sha256 "5da68afa721ebe5006db32624994713990c4a52e72889f1e86f08ff40a461562"

      def install
        bin.install "row"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suominentoni/row/releases/download/v0.1.0/row_0.1.0_linux_amd64.tar.gz"
      sha256 "fb95fe6c2e0f0a51009c0a78bec9caff3393b7705bec36f5eb6c8a071308e962"
      def install
        bin.install "row"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suominentoni/row/releases/download/v0.1.0/row_0.1.0_linux_arm64.tar.gz"
      sha256 "8348ea7e73220c51ee58e5f9b05dbea87ae991cdac0d5183f4a2d5b0c26169a6"
      def install
        bin.install "row"
      end
    end
  end
end
