# This file was generated by GoReleaser. DO NOT EDIT.
cask "row" do
  name "row"
  desc "Filter stdin lines by range"
  homepage "https://github.com/suominentoni/row"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "row"

  on_macos do
    on_intel do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_darwin_amd64.tar.gz"
      sha256 "4aac144bd4e1ceb7e27215ded9fa6687bc737b1ad230949970b62e16e5df24e0"
    end
    on_arm do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_darwin_arm64.tar.gz"
      sha256 "3cb6606a5ad99278f21d1a295da56b1d2dbc67e7ded911f68e66a9425a46ea90"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_linux_amd64.tar.gz"
      sha256 "06991bd21e51a793193f0184d42f8498ec5421d82c211897885f03dbf604ac9e"
    end
    on_arm do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_linux_arm64.tar.gz"
      sha256 "a84d476ed6cebf1cda61b3d14ad24f1ce9edbb9e42a97617bd53deb0cd2a6be9"
    end
  end

  # No zap stanza required
end
