# This file was generated by GoReleaser. DO NOT EDIT.
cask "row" do
  name "row"
  desc "Filter stdin lines by range"
  homepage "https://github.com/suominentoni/row"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "row"

  on_macos do
    on_intel do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_darwin_amd64.tar.gz"
      sha256 "6f743ab357e7b5883de54e5aff3f33afdabde95814d0d1ff86012d503552b7cc"
    end
    on_arm do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_darwin_arm64.tar.gz"
      sha256 "f681682568cf4a6a0e4b2ba71f965cbfc80ca29061dab4f2b2e3ff4afd338dcf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_linux_amd64.tar.gz"
      sha256 "d28634b2ce4dd586930036717561760c7820a2478b12a71036f0fe6dbb503454"
    end
    on_arm do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_linux_arm64.tar.gz"
      sha256 "7395414ef0abae050ac06047cbb539da086045ab8d7e22eb00f9b5559e3944b6"
    end
  end

  # No zap stanza required
end
