# This file was generated by GoReleaser. DO NOT EDIT.
cask "row" do
  name "row"
  desc "Filter stdin lines by range"
  homepage "https://github.com/suominentoni/row"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "row"

  on_macos do
    on_intel do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_darwin_amd64.tar.gz"
      sha256 "152986602d28de8bce1eebd506059000b59655bc31d1304ebd4b563122a3e9d3"
    end
    on_arm do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_darwin_arm64.tar.gz"
      sha256 "fd26a08262d75188753d57f448c23177bced30901e8183868a8109a6c9783cbb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_linux_amd64.tar.gz"
      sha256 "61806d80fea77654dfb2c748105f9e1459cb643c97023538354e643b35680884"
    end
    on_arm do
      url "https://github.com/suominentoni/row/releases/download/v#{version}/row_#{version}_linux_arm64.tar.gz"
      sha256 "d54a02778427ad6bde813d4c97bd380dcad5cb4e66da8d33a394f774c7746ad6"
    end
  end

  # No zap stanza required
end
